### ISSUE TITLE
Multi container pod

### ISSUE THREAD

**Issue by rmazlumyan** [tczekajlo/kube-consul-register#11]
Is there a way of specifying which container to register if i have a multi-container pod where both containers have ports defined and I only want one of those containers to register in consul ?

**Comment by tczekajlo** [comment]
No, there isn't, but such option seems to be a quite easy to implement. I'll take a look at it in spare time.

**Comment by tczekajlo** [comment]
In #13 I've added the ability to choose which container should be registered in the case when POD contains multi containers. I hope it will help.

**Comment by rmazlumyan** [comment]
@tczekajlo thanks for putting this feature so quickly. Looking forward to trying it out. 
Do you mind building a new docker image w/ the fix and pushing up a repository. Didn't see it at https://hub.docker.com/r/tczekajlo/kube-consul-register/tags/

**Comment by tczekajlo** [comment]
Sure. The new image is available on Docker Hub.
