### ISSUE TITLE
Possibility to specify tags?

### ISSUE THREAD

**Issue by cabrinoob** [tczekajlo/kube-consul-register#14]
Hi,
Is it possible to specify tags while registering services in consul? I'am familiar with registrator (gliderlabs/registrator) in which you can set a SERVICE_TAGS label to specify a tag list to use in consul.
Ex: SERVICE_TAGS="dev,1.0.0"

Thank you

**Comment by tczekajlo** [comment]
Hi,
Yes, it's possible. [Here](https://github.com/tczekajlo/kube-consul-register/blob/30c180635f362b37ef9ac5c3034562af36a53213/examples/nginx.yaml#L22) you can find an example. The rule is simple, every label (key) which has a value equal to "tag" will be added as a tag.

**Comment by tczekajlo** [comment]
@fastest963, what version of Kubernetes do you use and what value have you set in option `register_source`?

**Comment by fastest963** [comment]
Oh woops, I just updated my comment that it seems fixed now since I updated what container version I was using.
