### ISSUE TITLE
How do pods perform service discovery?

### ISSUE THREAD

**Issue by raffian** [tczekajlo/kube-consul-register#15]
We're experimenting with registration on kubernetes, but looking at this tool as alternative.
Some questions:

- Should kube-consul-register be setup as a daemonset?
- Where do pods connect to do service discovery; Consul, or kube-consul-register service? Normally, with Java we connect to Consul agent, but not sure if same approach should be used here.

**Comment by tczekajlo** [comment]
Not really. I recommend using replica set or deployment resource for kube-consul-register. 

Pods or being more precise applications connect to Consul Agent. In a case when you use single Consul Agent it's pretty easy, all applications will connect to one consul agent. Another an example is a case when you have consul agent in a pod as a container. It's still simple, you can use localhost as Consul address. Last option is having consul agent on each node. In this approaching, it's good to create service for consul agent and application can use an internal address of service.
