### ISSUE TITLE
Kubernetes Service registration

### ISSUE THREAD

**Issue by psyhomb** [tczekajlo/kube-consul-register#3]
Is there any chance to implement Kubernetes Service (with NodePort) registration as Consul Service instead or together with POD registration? These data can be very useful and can be further used to generate HAProxy configuration for external load balancing.

**Comment by tczekajlo** [comment]
Hi, It sounds like good idea. I'll take a look at this in next week.

**Comment by psyhomb** [comment]
Great, thanks man.

**Comment by tczekajlo** [comment]
In #5 I added support for Kubernetes Services, but without NodePort as you mentioned. I can't see any sense to register services with NodePort. If I associate correctly, using NodePort causes that an service is exposed on all nodes (or on the selected nodes) on given port, so what is the sense to register an service with NodePort. 

Maybe I don't understand something. Can you explain what you mean exactly when you mention registration with NodePort?

**Comment by psyhomb** [comment]
That's exactly the point of k8s [service](https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types) object with `type: NodePort`, to expose service port on every node in k8s cluster and to make service publicly (one step from HA) available (incoming traffic will be routed to backend pods by kube-proxy => iptables rules).

Then by using `consul-template` or `confd` it will be possible to retrieve this piece of information and use it to generate HAproxy configuration which will have frontend definition with some public network socket (probably floating IP + some port) and backend pool that will be composed from k8s worker nodes and NodePort, that way you will get an external load balancing for your service.

Btw this is something similar you will get with Kubernetes on AWS but far less flexible cause they are using ELB and ELB is not that configurable as HAproxy.

**Comment by tczekajlo** [comment]
OK. It's more clear for me now. I'll add support for NodePort, probably it'll be in next week.

**Comment by bobhenkel** [comment]
This is what I'm looking for too, I have an AWS VPC with our legacy services running it and they need to access the new services we migrate over to our AWS VPC running K8s.  Luckily we make heavy use of Consul in our legacy VPC and by peering the two VPCs together we can put node ip:node port entries in consul and the legacy services can route to the K8s services.

**Comment by tczekajlo** [comment]
I've been busy recently, so this issue took a while. In PR #8 I've added support for services with `NodePort` type.  [Here](https://github.com/tczekajlo/kube-consul-register/blob/master/examples/service_nodeport.yaml) you can find the example of service, additionally `register_source` option has to be set on `service`.
